name: onboarding
description: "GenSmile onboarding flow"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  gap: ^3.0.1
  sized_context: ^1.0.0+4
  flutter_svg: ^2.0.9
  flutter_validators: ^1.0.0
  intl: ^0.18.0
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
assets:
    - assets/images/
    - assets/svg/
